# Generated by Django 3.1.1 on 2020-09-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollno', models.IntegerField()),
                ('First_name', models.CharField(max_length=30)),
                ('Hint1', models.CharField(max_length=500)),
                ('time', models.CharField(max_length=50)),
            ],
        ),
    ]
