# Generated by Django 3.1.1 on 2020-09-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20200926_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='secret_Hint1',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friends',
            name='secret_Hint2',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friends',
            name='task',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
