# Generated by Django 3.1.1 on 2020-09-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20200927_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='url_link',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friends',
            name='verification',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
